version: '3.9'

networks:
  monitoring:
    driver: bridge

services:
  agent:
    build:
      context: ../../
      dockerfile: ./scripts/docker/nginx-oss/ubuntu/Dockerfile
      args:
        PACKAGE: ./build/nginx-agent
        AGENT_CONF: ./test/testdata/configs/integration/api/nginx-agent.conf
        NGINX_CONF: ./test/testdata/configs/integration/api/nginx.conf
        ENTRY_POINT: ./scripts/docker/nginx-oss/entrypoint.sh
    ports:
      - 8080:8080
      - 8081:8081
      - 9091:9091
    networks:
      - monitoring
